Reduce logging visibility of certain common, but not fatal issues.
Specifically:
1) Failure to set last access time. This is a frequent error with CIFS shares:
  WARNING: Failed to set the last access time for smb://172.25.51.22/share1/
  jcifs.smb.SmbException: Invalid operation for workgroups, servers, or shares
  I reduced the logging level to FINEST, without a stack trace.

2) It is no longer considered an error to not have a last modified date.
  I removed the code from AbstractReadonlyFile that throws an IOException
  if a file or directory has no last modified date. This is not an error.
  This should eliminate these types of log messages:
  WARNING: Failed to get last-modified time for file: smb://172.25.51.22/share1/
  java.io.IOException: Failed to get last modified time for smb://172.25.51.22/share1/

Not directly a fix for bug 6679622, but this makes makes it easier
to troubleshoot.

Code Review:
http://codereview.appspot.com/6300116