JCIFS retries broken connections
The customer frequently encounters these errors:

WARNING: Failed to feed document 
com.google.enterprise.connector.spi.RepositoryDocumentException: NT_STATUS_NOT_FOUND
	at com.google.enterprise.connector.filesystem.SmbReadonlyFile.newDelegate(SmbReadonlyFile.java:118)
	at com.google.enterprise.connector.filesystem.SmbReadonlyFile.<init>(SmbReadonlyFile.java:82)
	at com.google.enterprise.connector.filesystem.SmbReadonlyFile.newChild(SmbReadonlyFile.java:127)
	at com.google.enterprise.connector.filesystem.SmbReadonlyFile.newChild(SmbReadonlyFile.java:44)
	at com.google.enterprise.connector.filesystem.AbstractReadonlyFile.listFiles(AbstractReadonlyFile.java:236)
	at com.google.enterprise.connector.filesystem.AccessTimePreservingReadonlyFile.listFiles(AccessTimePreservingReadonlyFile.java:118)
	at com.google.enterprise.connector.filesystem.FileIterator.listFiles(FileIterator.java:205)
	at com.google.enterprise.connector.filesystem.FileIterator.setPositionToNextFile(FileIterator.java:114)
	at com.google.enterprise.connector.filesystem.FileIterator.hasNext(FileIterator.java:79)
	at com.google.enterprise.connector.filesystem.FileIterator.next(FileIterator.java:85)
	at com.google.enterprise.connector.filesystem.FileLister$Traverser.traverse(FileLister.java:444)
	at com.google.enterprise.connector.filesystem.FileLister$Traverser.call(FileLister.java:364)
	at com.google.enterprise.connector.filesystem.FileLister$Traverser.call(FileLister.java:342)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: jcifs.smb.SmbException: NT_STATUS_NOT_FOUND
	at jcifs.smb.SmbFile.resolveDfs(SmbFile.java:766)
	at jcifs.smb.SmbFile.send(SmbFile.java:775)
	at jcifs.smb.SmbFile.queryPath(SmbFile.java:1365)
	at jcifs.smb.SmbFile.exists(SmbFile.java:1420)
	at com.google.enterprise.connector.filesystem.SmbFileDelegate.isDirectory(SmbFileDelegate.java:160)
	at com.google.enterprise.connector.filesystem.SmbReadonlyFile.newDelegate(SmbReadonlyFile.java:110)
	... 17 more

WARNING: Failed to feed document 
com.google.enterprise.connector.spi.RepositoryDocumentException: The parameter is incorrect.
	at com.google.enterprise.connector.filesystem.SmbReadonlyFile.newDelegate(SmbReadonlyFile.java:118)
	at com.google.enterprise.connector.filesystem.SmbReadonlyFile.<init>(SmbReadonlyFile.java:82)
	at com.google.enterprise.connector.filesystem.SmbReadonlyFile.newChild(SmbReadonlyFile.java:127)
	at com.google.enterprise.connector.filesystem.SmbReadonlyFile.newChild(SmbReadonlyFile.java:44)
	at com.google.enterprise.connector.filesystem.AbstractReadonlyFile.listFiles(AbstractReadonlyFile.java:236)
	at com.google.enterprise.connector.filesystem.AccessTimePreservingReadonlyFile.listFiles(AccessTimePreservingReadonlyFile.java:118)
	at com.google.enterprise.connector.filesystem.FileIterator.listFiles(FileIterator.java:205)
	at com.google.enterprise.connector.filesystem.FileIterator.setPositionToNextFile(FileIterator.java:114)
	at com.google.enterprise.connector.filesystem.FileIterator.hasNext(FileIterator.java:79)
	at com.google.enterprise.connector.filesystem.FileIterator.next(FileIterator.java:85)
	at com.google.enterprise.connector.filesystem.FileLister$Traverser.traverse(FileLister.java:444)
	at com.google.enterprise.connector.filesystem.FileLister$Traverser.call(FileLister.java:364)
	at com.google.enterprise.connector.filesystem.FileLister$Traverser.call(FileLister.java:342)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: jcifs.smb.SmbException: The parameter is incorrect.
	at jcifs.smb.SmbTransport.checkStatus(SmbTransport.java:563)
	at jcifs.smb.SmbTransport.send(SmbTransport.java:640)
	at jcifs.smb.SmbSession.send(SmbSession.java:238)
	at jcifs.smb.SmbTree.send(SmbTree.java:119)
	at jcifs.smb.SmbFile.send(SmbFile.java:777)
	at jcifs.smb.SmbFile.queryPath(SmbFile.java:1365)
	at jcifs.smb.SmbFile.exists(SmbFile.java:1420)
	at com.google.enterprise.connector.filesystem.SmbFileDelegate.isDirectory(SmbFileDelegate.java:160)
	at com.google.enterprise.connector.filesystem.SmbReadonlyFile.newDelegate(SmbReadonlyFile.java:110)
	... 17 more


Once these errors start happening, they go on for a long string of transactions.
I am working on the assumption that the SmbSession and/or the SmbTransport has
gotten itself into an inconsistent state.  This is weakly backed up by JCIFS
author Mike Allen during a discussion of the NullPointerExceptions thrown out
of SmbFile.resolveDfs() [which we have also encountered].

This change, intended for an experimental build, attempts to intercept these
specific failures, destroy the connection, then retry the request after a 
short wait.

Code Review:
http://codereview.appspot.com/6851062